### ISSUE TITLE
todo 페이지 UI변경, 누락된 기능 추가

### ISSUE THREAD

**Issue by SongNoin** [wanted-pre-onboarding-fe-team-4/week1-todo-app#34]
## 할 일
- [ ] todo 페이지의 UI 변경
- [ ] todo update, delete 기능 추가
- [ ] todo 추가 시 ente로 입력 가능 하게 수정
